#pragma once

#include "../../src/curve.h"
#include "../../src/exceptions.h"
#include "../../src/old/helper.h"
#include "../../src/old/matrix.h"
#include "../../src/old/matrix_checks.h"
#include "../../src/old/matrix_decompositions.h"
#include "../../src/old/matrix_eigen.h"
#include "../../src/old/matrix_exceptions.h"
#include "../../src/old/matrix_general.h"
#include "../../src/old/matrix_operators.h"
#include "../../src/old/matrix_transformations.h"
#include "../../src/old/vector.h"
#include "../../src/vector_checks.h"
#include "../../src/old/vector_general.h"
#include "../../src/old/vector_operators.h"
#include "../../src/old/vertex.h"
